insert into Course (ID, Department_NAME, Name) values (152, 'Engineering and Natural Sciences', 'Fundamentals of Programming');
insert into Course (ID, Department_NAME, Name) values (165, 'Engineering and Natural Sciences', 'Linear Aladbra');
insert into Course (ID, Department_NAME, Name) values (138, 'Engineering and Natural Sciences', 'Mathematics for Computer Science');
insert into Course (ID, Department_NAME, Name) values (140, 'Engineering and Natural Sciences', 'Physical Education');
insert into Course (ID, Department_NAME, Name) values (126, 'Engineering and Natural Sciences', 'Modern History of Kazakhstan');
insert into Course (ID, Department_NAME, Name) values (175, 'Engineering and Natural Sciences', 'Programming Technologies and Educational Practice');
insert into Course (ID, Department_NAME, Name) values (113, 'Engineering and Natural Sciences', 'Information and Communications Technologies');
insert into Course (ID, Department_NAME, Name) values (127, 'Engineering and Natural Sciences', 'Discrete Mathematics');
insert into Course (ID, Department_NAME, Name) values (183, 'Engineering and Natural Sciences', 'Physics');
insert into Course (ID, Department_NAME, Name) values (153, 'Engineering and Natural Sciences', 'Introduction to Algorithms');
insert into Course (ID, Department_NAME, Name) values (177, 'Engineering and Natural Sciences', 'Database Management Systems');
insert into Course (ID, Department_NAME, Name) values (174, 'Engineering and Natural Sciences', 'Web programming: front end');
insert into Course (ID, Department_NAME, Name) values (141, 'Engineering and Natural Sciences', '');
insert into Course (ID, Department_NAME, Name) values (148, 'Engineering and Natural Sciences', 'Fundamentals of Programming');
insert into Course (ID, Department_NAME, Name) values (241, 'Business School', 'Digital Marketing');
insert into Course (ID, Department_NAME, Name) values (228, 'Business School', 'Management');
insert into Course (ID, Department_NAME, Name) values (250, 'Business School', 'Finance');
insert into Course (ID, Department_NAME, Name) values (214, 'Business School', 'Economics');
insert into Course (ID, Department_NAME, Name) values (262, 'Business School', 'Accounting and Audit');
insert into Course (ID, Department_NAME, Name) values (281, 'Business School', 'Financial Technology');
insert into Course (ID, Department_NAME, Name) values (201, 'Engineering and Natural Sciences', 'Preschool training');
insert into Course (ID, Department_NAME, Name) values (262, 'Engineering and Natural Sciences', 'psychology');
insert into Course (ID, Department_NAME, Name) values (215, 'Engineering and Natural Sciences', 'Social pedagogy');
insert into Course (ID, Department_NAME, Name) values (275, 'Engineering and Natural Sciences', 'Pedagogics');
insert into Course (ID, Department_NAME, Name) values (209, 'Engineering and Natural Sciences', 'History');
insert into Course (ID, Department_NAME, Name) values (267, 'Engineering and Natural Sciences', 'Mathematics');
insert into Course (ID, Department_NAME, Name) values (239, 'Engineering and Natural Sciences', 'Physics');
insert into Course (ID, Department_NAME, Name) values (253, 'Engineering and Natural Sciences', 'Physical Education');
insert into Course (ID, Department_NAME, Name) values (225, 'Engineering and Natural Sciences', 'Fundamentals of Programming');
insert into Course (ID, Department_NAME, Name) values (263, 'Engineering and Natural Sciences', 'Linear Aladbra');
insert into Course (ID, Department_NAME, Name) values (261, 'Law and Social Sciences', 'Journalism and Design');
insert into Course (ID, Department_NAME, Name) values (310, 'Law and Social Sciences', 'History');
insert into Course (ID, Department_NAME, Name) values (251, 'Law and Social Sciences', 'Applied law');
insert into Course (ID, Department_NAME, Name) values (228, 'Law and Social Sciences', 'International Law');
insert into Course (ID, Department_NAME, Name) values (267, 'Law and Social Sciences', 'Law of Public administration');
insert into Course (ID, Department_NAME, Name) values (240, 'Law and Social Sciences', 'Private Law');
insert into Course (ID, Department_NAME, Name) values (257, 'Law and Social Sciences', 'Information Technology Law');
insert into Course (ID, Department_NAME, Name) values (229, 'Law and Social Sciences', 'Public Law');
insert into Course (ID, Department_NAME, Name) values (264, 'Law and Social Sciences', 'International Relations');