insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (round(rand() * 200) , 'Eloisa Cauley', 'Administration', 38, 500000, 'Rector', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (round(rand() * 200), 'Barbabas Manilo', 'Administration', 59, 450000, 'Rector', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (round(rand() * 200), 'Jereme Romand', 'Administration', 41, 500000, 'Department Head', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (round(rand() * 200), 'Finn Powrie', 'Administration', 41, 500000, 'Department Head', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (round(rand() * 200), 'Winonah Merveille', 'Administration', 54, 340000, 'Accountant', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (round(rand() * 200), 'Nollie Essame', 'Administration', 35, 450000, 'Department Head', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (round(rand() * 200), 'Thelma Coverdill', 'Administration', 56, 450000, 'Department Head', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (round(rand() * 200), 'Laurent Fabbro', 'Administration', 31, 450000, 'Department Head', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (183, 'Zeb Scrimshaw', 'Cleaner', 56, 240000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (264, 'Ethelin Coller', 'Security', 40, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (183, 'Olive MacMurray', 'Cleaner', 60, 260000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (283, 'Margaretha Kierans', 'Security', 55, 220000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (295, 'Nikos Chapelle', 'Cleaner', 52, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (105, 'Gilberte Newbigging', 'Cleaner', 38, 220000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (239, 'Kirby Celez', 'Cleaner', 38, 260000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (253, 'Adrianne Starbuck', 'Security', 32, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (233, 'Niven Davie', 'Security', 43, 220000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (106, 'Gwendolyn Josuweit', 'Security', 47, 260000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (100, 'Fredrika Rape', 'Security', 57, 240000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (157, 'Sallyann Evitt', 'Cleaner', 32, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (212, 'Honoria Cham', 'Security', 42, 220000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (149, 'Rodolph Hinchon', 'Cleaner', 45, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (264, 'Kai Goude', 'Security', 51, 240000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (103, 'Lynelle Davey', 'Cleaner', 42, 240000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (294, 'Sherwynd Brittin', 'Cleaner', 31, 260000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (182, 'Melodee Rubertelli', 'Security', 30, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (109, 'Marwin Evers', 'Security', 49, 240000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (208, 'Amberly Oldroyde', 'Security', 39, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (240, 'Hervey Mussolini', 'Cleaner', 44, 240000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (234, 'Kalindi D''Antoni', 'Security', 45, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (127, 'Andreana Veryard', 'Security', 60, 260000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (225, 'Lenka Hannam', 'Security', 31, 240000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (181, 'Lavena Southcombe', 'Cleaner', 39, 220000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (280, 'Dalia Nevet', 'Cleaner', 45, 220000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (184, 'Ronalda Gabb', 'Security', 36, 240000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (165, 'Genvieve Hattoe', 'Security', 51, 260000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (135, 'Titus Jursch', 'Cleaner', 32, 220000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (206, 'Donnamarie Creer', 'Cleaner', 57, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (258, 'Henrie Gellion', 'Security', 54, 220000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (111, 'Cassondra Scotchmur', 'Security', 30, 240000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (231, 'Marian Rassell', 'Security', 38, 240000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (102, 'Justus Ullock', 'Cleaner', 46, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (253, 'Pamelina Newman', 'Cleaner', 51, 220000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (151, 'Gabriella Doppler', 'Security', 35, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (195, 'Genia Pavitt', 'Security', 55, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (274, 'Toby Bignall', 'Security', 50, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (129, 'Pembroke Curnnokk', 'Security', 33, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (185, 'Mariann Nannini', 'Security', 45, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (188, 'Culley Powland', 'Cleaner', 34, 220000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (105, 'Cassey Haddleton', 'Cleaner', 50, 180000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (219, 'Gonzalo MacCourt', 'Cleaner', 40, 240000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (166, 'Tiffany Fardy', 'Cleaner', 46, 260000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (296, 'Hort O''Crevy', 'Cleaner', 59, 260000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (156, 'Catlaina Allcorn', 'Security', 42, 240000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (255, 'Marylinda Colloby', 'Security', 32, 240000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (143, 'Georas Shrawley', 'Security', 53, 260000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (174, 'Neville Wonfor', 'Security', 49, 220000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (278, 'Queenie Ferrao', 'Security', 47, 240000, 'NONE', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (204, 'Dorian Lamcken', 'Administration', 30, 240000, 'Manager', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (252, 'Solly Ive', 'Administration', 38, 280000, 'Manager', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (265, 'Nicolea Roocroft', 'Administration', 29, 240000, 'Manager', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (289, 'Dorian Beggin', 'Administration', 29, 240000, 'Manager', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (208, 'Blondy Borton', 'Administration', 31, 280000, 'Manager', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (219, 'Maxim Buckam', 'Administration', 26, 240000, 'Manager', (Select room from Emp_room order by rand() limit 1));
insert into Employee (id, Name, Type, Age, Salary, Special, Emp_room) values (214, 'Ermentrude Vasilic', 'Administration', 33, 280000, 'Manager', (Select room from Emp_room order by rand() limit 1));
