insert into employee  values (1, 'Dorie Murrell', 'Instructor', 39, 300000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (2, 'Hasheem Hunnisett', 'Instructor', 52, 340000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (3, 'Sadella Tizard', 'Instructor', 26, 220000, 'Business School', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (4, 'Randell Velten', 'Instructor', 31, 340000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (5, 'Luther Hancorn', 'Instructor', 49, 300000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (6, 'Lance Wittleton', 'Instructor', 40, 240000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (7, 'Wynne Webb', 'Instructor', 64, 200000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (8, 'Marlin Tretter', 'Instructor', 64, 240000, 'Business School', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (9, 'Sumner Charity', 'Instructor', 37, 340000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (10, 'Rafaelita Reed', 'Instructor', 43, 280000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (11, 'Ariel Woodbridge', 'Instructor', 24, 200000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (12, 'Marika Guinn', 'Instructor', 66, 280000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (13, 'Jessamyn Lowdeane', 'Instructor', 33, 300000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (14, 'Margaret Aguirrezabala', 'Instructor', 57, 200000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (15, 'Susannah Lawlie', 'Instructor', 60, 280000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (16, 'Laraine Rostron', 'Instructor', 26, 300000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (17, 'Richie Rolles', 'Instructor', 52, 280000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (18, 'Merla Dawe', 'Instructor', 41, 300000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (19, 'Berni Dandy', 'Instructor', 30, 280000, 'Business School', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (20, 'Lucius Gyorgy', 'Instructor', 63, 240000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (21, 'Ursola Cruikshanks', 'Instructor', 61, 200000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (22, 'Georgeanna Barense', 'Instructor', 36, 280000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (23, 'Bendick Marrington', 'Instructor', 49, 220000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (24, 'Barri McIlherran', 'Instructor', 27, 200000, 'Business School', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (25, 'Hakeem Walklott', 'Instructor', 56, 240000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (26, 'Ted Fulop', 'Instructor', 27, 340000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (27, 'Valeria Butteris', 'Instructor', 49, 200000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (28, 'Freeman Matthieson', 'Instructor', 26, 240000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (29, 'Agata Ferraretto', 'Instructor', 52, 300000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (30, 'Keely Neame', 'Instructor', 41, 220000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (31, 'Benoite Jeynes', 'Instructor', 61, 200000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (32, 'Christiana Andreutti', 'Instructor', 40, 280000, 'Business School', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (33, 'Vernor Meiklem', 'Instructor', 44, 220000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (34, 'Katti MacCartan', 'Instructor', 48, 220000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (35, 'Avivah Riches', 'Instructor', 36, 240000, 'Business School', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (36, 'Thorstein Jakoub', 'Instructor', 34, 300000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (37, 'Ignaz Bagshawe', 'Instructor', 41, 220000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (38, 'Lexis Mallinson', 'Instructor', 53, 200000, 'Business School', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (39, 'Nixie Osgood', 'Instructor', 34, 340000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (40, 'Gloria McIlvaney', 'Instructor', 44, 220000, 'Business School', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (41, 'Jordanna Louedey', 'Instructor', 37, 340000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (42, 'Danya Ivanitsa', 'Instructor', 62, 280000, 'Business School', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (43, 'Nichol Stoite', 'Instructor', 57, 240000, 'Business School', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (44, 'Emmit Paulig', 'Instructor', 58, 280000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (45, 'Binni Renvoys', 'Instructor', 39, 280000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (46, 'Juliana Kilbane', 'Instructor', 64, 200000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (47, 'Roxanne Fanshawe', 'Instructor', 26, 240000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (48, 'Farrel Ortner', 'Instructor', 54, 240000, 'Business School', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (49, 'Tulley Champagne', 'Instructor', 36, 200000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (50, 'Derwin Finn', 'Instructor', 28, 220000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (51, 'Miriam Blezard', 'Instructor', 31, 300000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (52, 'Mortimer Boeter', 'Instructor', 43, 300000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (53, 'Wynn Wyldish', 'Instructor', 54, 300000, 'Business School', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (54, 'Edeline Thirst', 'Instructor', 24, 280000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (55, 'Cathrin Lghan', 'Instructor', 36, 300000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (56, 'Gale Kirkham', 'Instructor', 49, 220000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (57, 'Flynn Hurlston', 'Instructor', 27, 300000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (58, 'Ajay Mangeon', 'Instructor', 49, 240000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (59, 'Meridith Joannic', 'Instructor', 41, 340000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (60, 'Tiffie Gisborne', 'Instructor', 43, 280000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (61, 'Sophey Hyndson', 'Instructor', 41, 240000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (62, 'Fanchon Ridgeway', 'Instructor', 61, 280000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (63, 'Lawton Lys', 'Instructor', 40, 280000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (64, 'Darrell Trevaskis', 'Instructor', 51, 220000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (65, 'Slade Biddell', 'Instructor', 57, 240000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (66, 'Beck Feetham', 'Instructor', 64, 200000, 'Education and Humanities', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (67, 'Callida Airth', 'Instructor', 45, 280000, 'Engineering and Natural Sciences', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (68, 'Rodrick Eyer', 'Instructor', 30, 240000, 'Business School', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (69, 'Eva Goodings', 'Instructor', 26, 240000, 'Business School', (Select room from Emp_room order by rand() limit 1));
insert into employee  values (70, 'Marchall Poile', 'Instructor', 51, 340000, 'Law and Social Sciences', (Select room from Emp_room order by rand() limit 1));
